const data = {
  products: [
    {
      _id: '1',
      name: 'model1',
      slug: 'model-1',
      category: 'test',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 5,
      brand: 'test',
      rating: 5,
      numRevies: 4,
      description: 'product model description',
    },
    {
      _id: '2',
      name: 'model2',
      slug: 'model-2',
      category: 'test',
      image: '/images/p2.jpg',
      price: 60,
      countInStock: 10,
      brand: 'test',
      rating: 4,
      numRevies: 24,
      description: 'product model 2 description',
    },
    {
      _id: '3',
      name: 'model3',
      slug: 'model-3',
      category: 'test',
      image: '/images/p1.jpg',
      price: 100,
      countInStock: 5,
      brand: 'test',
      rating: 5,
      numRevies: 4,
      description: 'product model description',
    },
    {
      _id: '4',
      name: 'model4',
      slug: 'model-4',
      category: 'test',
      image: '/images/p2.jpg',
      price: 60,
      countInStock: 0,
      brand: 'test',
      rating: 4,
      numRevies: 24,
      description: 'product model 2 description',
    },
  ],
};

export default data;
